# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0

# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY CRUD_SERVLET1.2.war /usr/local/tomcat/webapps/
COPY REPORTES_JSP_v1.4.war CRUD_SERVLET1.2.war /usr/local/tomcat/webapps/

